In [18]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census
from us import states

# Census API Key
from config import api_key
c = Census(api_key, year=2013)

In [19]:
# Run Census Search to retrieve data on all states (2013 ACS5 Census)
census_data = c.acs5.get(("NAME", "B19013_001E", "B01003_001E", "B01002_001E",
                          "B19301_001E",
                          "B01001_002E", "B01001_026E"), {'for':'state:*'})

# Convert to DataFrame
census_pd = pd.DataFrame(census_data)

# Column Reordering
census_pd = census_pd.rename(columns={"B01003_001E": "Population",
                                      "B01002_001E": "Median Age",
                                      "B19013_001E": "Household Income",
                                      "B19301_001E": "Per Capita Income",
                                      "B01001_002E": "Number of Males",
                                      "B01001_026E": "Number of Females",
                                      "NAME": "Name", 
                                      "State": "state"})


# Final DataFrame
census_pd = census_pd[["Name", "Population", "Median Age", "Household Income",
                       "Per Capita Income", "Number of Males", "Number of Females"]]

# Visualize
print(len(census_pd))
census_pd.head()

52

,Name,Population,Median Age,Household Income,Per Capita Income,Number of Males,Number of Females
0,Alabama,4799277.0,38.1,43253.0,23680.0,2328592.0,2470685.0
1,Alaska,720316.0,33.6,70760.0,32651.0,375798.0,344518.0
2,Arizona,6479703.0,36.3,49774.0,25358.0,3221367.0,3258336.0
3,Arkansas,2933369.0,37.5,40768.0,22170.0,1439862.0,1493507.0
4,California,37659181.0,35.4,61094.0,29527.0,18726468.0,18932713.0

In [20]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_pd.to_csv("census_data.csv", encoding="utf-8", index=False)